// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsz0_DDqCOI_2DzNWeqk4OR8GKZ_cSi3Q',
    appId: '1:1035608044842:web:d620a417350f06d740da53',
    messagingSenderId: '1035608044842',
    projectId: 'flutter-base-de-datos-ed70a',
    authDomain: 'flutter-base-de-datos-ed70a.firebaseapp.com',
    storageBucket: 'flutter-base-de-datos-ed70a.firebasestorage.app',
    measurementId: 'G-C57CTS1RBJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwK9EFF6m1w_0PV0GXvYleOhiC4YQASeE',
    appId: '1:1035608044842:android:62561df301b433bf40da53',
    messagingSenderId: '1035608044842',
    projectId: 'flutter-base-de-datos-ed70a',
    storageBucket: 'flutter-base-de-datos-ed70a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtygL-HNqiDKSP4_Cyhqb7ca7MAKABJOo',
    appId: '1:1035608044842:ios:083f5f4acfc670ce40da53',
    messagingSenderId: '1035608044842',
    projectId: 'flutter-base-de-datos-ed70a',
    storageBucket: 'flutter-base-de-datos-ed70a.firebasestorage.app',
    iosBundleId: 'com.example.taully',
  );
}
